language: nix

sudo: true

git:
  depth: 1

env:
  global:
  matrix:
    - GHCVERSION=ghc802
    - GHCVERSION=ghc822
    - GHCVERSION=ghc843
    - GHCVERSION=ghc884
    - GHCVERSION=ghc8104

matrix:
  allow_failures:
  exclude:

script:
  - nix-build release.nix --argstr compiler $GHCVERSION

branches:
  only:
    - master
